language: csharp
solution: DTORepository.sln
install:
  - nuget restore DTORepository.sln
  - nuget install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release DTORepository.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./DTORepositoryTest/bin/Release/DTORepositoryTest.dll
