language: csharp
solution: DTORepository.sln
before_install:
  - mkdir -p .nuget
  - wget -O .nuget/nuget.exe https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
  - mono .nuget/nuget.exe # Output NuGet's version number
install:
  - mono .nuget/nuget.exe restore DTORepository.sln -Verbosity detailed
  - mono .nuget/nuget.exe install xunit.runners -Version 1.9.2 -OutputDirectory testrunner
  - ls /home/travis/.nuget/packages/automapper
script:
  - MONO_IOMAP=case xbuild /p:Configuration=Release DTORepository.sln
  - mono ./testrunner/xunit.runners.1.9.2/tools/xunit.console.clr4.exe ./DTORepositoryTest/bin/Release/DTORepositoryTest.dll
