install:
  - nuget restore DTORepository.sln -Verbosity detailed
  - nuget install xunit.runner.console -Version 2.2.0 -OutputDirectory testrunner

configuration: Release

build:
  project: DTORepository.sln
  verbosity: detailed

test_script:
  - ./testrunner/xunit.runner.console.2.2.0/tools/xunit.console.exe ./DTORepositoryTest/bin/Release/DTORepositoryTest.dll
